### PR TITLE
Ready for usd-23.05

### PR DESCRIPTION
**Pull request by SebSchmidtWetaFx**
makes the necessary updates to compile with use-23.05

### CODE REVIEW

**Comment by kenanbolukbasi-w** [comment]
@SebSchmidtWetaFx Looks good!

**Comment by rlei-weta** [comment]
Thanks for this @SebSchmidtWetaFx, may you please update all the instances of 22.08 mentioned in the README (or in any other file throughout the repo) to 23.05?  Cheers

**Comment by rlei-weta** [comment]
@SebSchmidtWetaFx may you also please:
- run clang-format on the code base, and
- run usd-23.05's usdGenSchema on `src/usdTri`

**Comment by rlei-weta** [comment]
Closing as commit was merged as part of #42

**Pull request closed without merging**
